version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend-web-musica
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: backend-api-musica
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always