services:
  - type: web
    name: mp3-downloader-backend
    env: docker
    plan: free
    docker:
      dockerfilePath: backend/Dockerfile
      context: backend

  - type: web
    name: mp3-downloader-frontend
    env: docker
    plan: free
    docker:
      dockerfilePath: frontend/Dockerfile
      context: frontend